import '../styles/globals.css'
import Head from 'next/head'
import {SnackbarProvider } from 'notistack';

const connectDB = require("../util/connection");

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>PSG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SnackbarProvider maxSnack={3}>
        <Component {...pageProps} />
      </SnackbarProvider>
    </>
  )
}

export default MyApp
