import '../styles/globals.css'
import Head from 'next/head'

const connectDB = require("../util/connection");

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>PSG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
