import Head from 'next/head'
import styles from '../styles/Home.module.css'

import useSWR from 'swr'
import axios from 'axios'

import { Sidebar } from '../components'

export default function Home() {

  const { data: courses, error: cousesError } = useSWR('/api/courses', url => axios.get(url, {
    params: {
      option: "sidebar"
    }
  }))

  const { data: tools, error: toolsError } = useSWR('/api/tools', axios.get)

  if (cousesError || toolsError) return <div>failed to load</div>
  if (!courses && !tools) return <div>loading...</div>

  console.log("TOOLS")
  console.log(tools)

  return (
    <>
        <Head>
          <title>PSG</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Sidebar courses={courses.data} tools={tools.data}/>
    </>
  )
}
